-- 코드를 작성해주세요
# 먼저 연도별 가장 큰 사이즈를 구해두어야 한다
# with를 이용해 테이블을 생성한다
WITH MAX_SIZE_BY_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT S.YEAR, (S.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM MAX_SIZE_BY_YEAR S, ECOLI_DATA E
WHERE S.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC;