/*
    2022년 1월의 카테고리별 도서 판매량을 합산하고, CATEGORY, TOTAL_SALES를 출력하자
*/


SELECT R.CATEGORY, SUM(R.SALES) AS TOTAL_SALES
FROM (
    SELECT 
        B.BOOK_ID,
        B.CATEGORY,
        SUM(S.SALES) AS SALES
    FROM BOOK B
    JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY B.BOOK_ID
    ORDER BY B.BOOK_ID ASC
) AS R
GROUP BY R.CATEGORY
ORDER BY R.CATEGORY ASC;


